# Generated by Django 6.0.3 on 2026-04-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Lectures'),
        ),
    ]
