# Generated by Django 6.0.3 on 2026-04-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Lien public Google Drive de la couverture', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_file_url',
            field=models.URLField(blank=True, help_text='Lien public Google Drive du fichier EPUB', max_length=500),
        ),
    ]
