# Generated by Django 6.0.3 on 2026-04-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options_book_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='epub_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='epub_file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
