# Generated by Django 6.0.3 on 2026-04-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover_image_id_book_epub_file_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-is_featured', '-featured_order', '-created_at'], 'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
        migrations.AddField(
            model_name='book',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mis en avant'),
        ),
    ]
