# Generated by Django 6.0.3 on 2026-04-26 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Solde (FCFA)')),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('basic', 'Basic (500 FCFA/mois)'), ('premium', 'Premium (1000 FCFA/mois)')], default='free', max_length=20, verbose_name='Forfait')),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiration du forfait')),
                ('total_spent', models.PositiveIntegerField(default=0, verbose_name='Total dépensé (FCFA)')),
                ('books_read', models.PositiveIntegerField(default=0, verbose_name='Livres lus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Recharge'), ('subscription', 'Abonnement'), ('refund', 'Remboursement'), ('bonus', 'Bonus')], max_length=20, verbose_name='Type')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Méthode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userprofile')),
            ],
        ),
    ]
