# Generated by Django 6.0.3 on 2026-04-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0002_book_reads_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='purchased_books',
            field=models.ManyToManyField(blank=True, related_name='purchasers', to='books.book', verbose_name='Livres achetés'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Recharge'), ('subscription', 'Abonnement'), ('purchase', 'Achat unitaire'), ('refund', 'Remboursement'), ('bonus', 'Bonus')], max_length=20, verbose_name='Type'),
        ),
    ]
